### ISSUE TITLE
dq_render_handsontable trouble showing all of the column filters

### ISSUE THREAD

**Issue by FrankSchiro** [daqana/dqshiny#13]
I'm having a problem where I can't get dq_render_handsontable to show all of the column filters. 

The filters cut off around the 5th or 6th filter

![image](https://user-images.githubusercontent.com/45154120/83084063-df76f180-a055-11ea-9c8a-46694b1191fe.png)

Could someone please help me out?

```
df = data.frame(hello1 = c("apple", "monkey", "carot", "potato"), stringsAsFactors = FALSE)
df2 = df
for(i in 1:20){
    df = cbind(df, df2)
}
names(df) = paste0(names(df), seq(20))

shinyApp(
    ui = fluidPage(
        dq_handsontable_output("randomTable")
    ),
    server = function(input, output, session) {
        dq_render_handsontable(
            "randomTable", 
            df,
            filters = "T",
            page_size = NULL,
            width_align = TRUE,
            horizontal_scroll = TRUE,
            table_param = list(width = (300 * ncol(df)))
        )
    }
)

```

**Comment by richardkunze** [comment]
Hi there. Those filters are cut off because they exceed the pages container.

You can add the following line at the start of your UI (or just add the style to any CSS file you may include in your app) to disable the cut off:
`tags$head(tags$style("#randomTable-filters {overflow:visible !important;}")),`

I hope it works well you.

**Comment by FrankSchiro** [comment]
Thanks! This fixed the problem1
