### ISSUE TITLE
Autocomplete - Changing one autocomplete_input changes all other ones that contain that value in their options

### ISSUE THREAD

**Issue by ezpzlmnsqzy2** [daqana/dqshiny#14]
I have a few autocomplete_input boxes that all have the same set of options. Changing one of these boxes changes all of them to the same value. Is this intended behavior? Is there a way to keep their values seperate?

For a complete example, the official example (https://rdrr.io/cran/dqshiny/man/autocomplete_input.html) actually suffers from this problem as well when I copy it into RStudio and run it.

**Comment by richardkunze** [comment]
Hi there, I was actually working on the autocomplete input these days and noticed things like that. That's why I would like you to check if your issue is fixed in the current github version. You can install the newest version with: `remotes::install_github("daqana/dqshiny")`

If you can't install the dev version, you can wait for CRAN release next week.

**Comment by ezpzlmnsqzy2** [comment]
Awesome! The latest Github version solves this problem.
