### ISSUE TITLE
Display full list of options regardless of match?

### ISSUE THREAD

**Issue by ezpzlmnsqzy2** [daqana/dqshiny#15]
I recognize this may be a rare use case, but is there currently a way to display the full list of options rather than matching them based on input, or alternatively a way to override the way the options list filters things out? If not, is there another UI component that might fit this use case better?

For example, if my recommendations are "option1" and "option2", and i type "boat" I would like to still have the recommendations show under the text input.

**Comment by richardkunze** [comment]
Hi there, sorry for the late response.

Normally showing all options wouldn't be a good idea since rendering thousands of elements can be very slowly. I could add a parameter to show all elements if input is empty or no matches are found but there wouldn't be any advantage against normal `shiny::selectInput`. So I'd recommend you to use the original `selectInput` instead.
