### ISSUE TITLE
autocomplete not really autocomplete

### ISSUE THREAD

**Issue by AzlinII** [daqana/dqshiny#4]
While the autocomplete does allow you to write in words that are not part of the choices, I am not actually able to get the value typed in. When testing it with a button to try and get the value I typed in, I get an empty string instead of the value typed in.

**Comment by richardkunze** [comment]
Yes, the value of the input element only changes if a word was correctly selected from the list of allowed words. That's intended in order to let shiny (and you) know, that the chosen word is valid. Otherwise you would have to check if the current value is in the list of proper words, which is already done on the JS side.

If you explicitly need this feature I could add a new parameter to the autocomplete_input to activate update on every change.

**Comment by AzlinII** [comment]
I believe this feature would be a nice feature to have. While I have been making due with `selectizeInput(options = list(create = TRUE))`, I think your autocomplete would be easier to use for end users.

**Comment by richardkunze** [comment]
Just added a create parameter to enable shiny input updates on whatever you type in the text field. I hope everything is working as expected.
