### ISSUE TITLE
autocomplete_input update options dynamically

### ISSUE THREAD

**Issue by chrisvwn** [daqana/dqshiny#7]
Thank you for the useful package.

Is it possible to update the options of the component dynamically as the user types rather than sourcing from a static list? One possible way is to enable one to set up an observeEvent that triggers as the user types or when they pause allowing them to run an `update_autocomplete_input`? Alternatively, have an option to update the options maybe when the user pauses typing?

I know the component solves the problem of slow large option lists, so this may not be a direct use case for it.

**Comment by richardkunze** [comment]
Hi, there. I think your desired behaviour should already be possible if you use `create = TRUE`. In this case there will be an event while typing. The only downside is that you will have to check on your own if a value is selected.

Please have a look at this example and tell me if it fits your needs (although it's probably a bad idea to select options randomly ;) ). Otherwise I will have a closer look at it and try to find a proper solution. I think It shouldn't be much of a problem to add another type of event while typing and show the options after update from the server.

```
opts <- rownames(mtcars)
shinyApp(
  ui = fluidPage(
    shiny::titlePanel("Changing options while typing"),
    fluidRow(column(
      3, autocomplete_input("auto", NULL, opts[1:10], max_options = 250, create = TRUE)
    ))
  ),
  server = function(input, output, session) {
    observeEvent(input$auto, {
      update_autocomplete_input(session, "auto", options = opts[sample(length(opts), 10)])
    })
  }
)
```

**Comment by chrisvwn** [comment]
Thanks @richardkunze This works very nicely!

So I was trying to simulate a google maps search box and using the googleway package this works so well! I had requested this functionality on the googleway github page and we didn't get a good answer. Combining this with the `googleway::google_place_autocomplete()` function works neatly!

For reference, this is what I finally got working and with surprisingly little effort!
```
library(shiny)
library(dqshiny)

shinyApp(
  ui = fluidPage(
    shiny::titlePanel("A Shiny google maps search box"),
    fluidRow(column(
      3, autocomplete_input("auto", NULL, opts[1:10], max_options = 250, create = TRUE)
    ))
  ),
  server = function(input, output, session) {
    observeEvent(input$auto, {
      optPlaces <- googleway::google_place_autocomplete(input$auto, key = "xxxxxxxxxxx")
      update_autocomplete_input(session, "auto", options = optPlaces$predictions[,"description"])
    }, ignoreInit = TRUE)
  }
)
```

**Comment by richardkunze** [comment]
I'm glad that I could help!

**Comment by shashj** [comment]
this does not work now
